import { Inter  } from "next/font/google";

import Header from "../components/header/header1";
import Footer from "../components/footer/footer";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CondosLayout({ children }) {
  return (

      <>
       {children}
      </>
        
       
        
      
  );
}
